# App
spring.application.name=${SPRING_APP_NAME}-test
spring.main.banner-mode=off
server.port=${HOST_PORT}
logging.level.root=WARN
logging.level.org.springframework=WARN

# Security
jwt.secret=mock-test-secret-key-123
jwt.issuer=mock-test-issuer
jwt.public=/**
jwt.expiration=216000

# Test Database
spring.datasource.url=jdbc:h2:mem:auth;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=test-user
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=false

# OpenAPI / Swagger
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Eureka
eureka.client.enabled=false
