# Documentation Metadata
springdoc.openapi.info.title=Auth Microservice API
springdoc.openapi.info.version=v0.1
springdoc.openapi.info.description=This microservice handles autentication & JWT operations.
